// Effects database - from Nightreign Effect Data spreadsheet
// Source: https://docs.google.com/spreadsheets/d/1Gz6fqIBNr2BXr45te9ewTolHJr4zZ_Apbqa09gL3VbI
// Generated: 2026-02-06
// Total: 546 relic effects
const EFFECTS_DB = [
  { id: 10000, name: "FP Restoration upon Successive Attacks", desc: "Restores 5% of max FP after continuous attacks. Only affects melee attacks." },
  { id: 10001, name: "Taking attacks improves attack power", desc: "15% damage buff after taking a hit. Lasts for for 10 seconds. Duration refreshes when getting hit again. Does not trigger if hit was blocked." },
  { id: 6001400, name: "Physical Attack Up +3", desc: "Increases physical damage by 10.5%" },
  { id: 6001401, name: "Physical Attack Up +4", desc: "Increases physical damage by 12%" },
  { id: 6001500, name: "Magic Attack Power Up +3", desc: "Increases magic damage 10.5%" },
  { id: 6001501, name: "Magic Attack Power Up +4", desc: "Increases magic damage 12%" },
  { id: 6001600, name: "Fire Attack Power Up +3", desc: "Increases fire damage 10.5%" },
  { id: 6001601, name: "Fire Attack Power Up +4", desc: "Increases fire damage 12%" },
  { id: 6001700, name: "Lightning Attack Power Up +3", desc: "Increases lightning damage 10.5%" },
  { id: 6001701, name: "Lightning Attack Power Up +4", desc: "Increases lightning damage 12%" },
  { id: 6001800, name: "Holy Attack Power Up +3", desc: "Increases holy damage 10.5%" },
  { id: 6001801, name: "Holy Attack Power Up +4", desc: "Increases holy damage 12%" },
  { id: 6002600, name: "Improved Magic Damage Negation +1", desc: "Increases magic damage negation by 15%" },
  { id: 6002601, name: "Improved Magic Damage Negation +2", desc: "Increases magic damage negation by 16%" },
  { id: 6002700, name: "Improved Fire Damage Negation +1", desc: "Increases fire damage negation by 15%" },
  { id: 6002701, name: "Improved Fire Damage Negation +2", desc: "Increases fire damage negation by 16%" },
  { id: 6002800, name: "Improved Lightning Damage Negation +1", desc: "Increases lightning damage negation by 15%" },
  { id: 6002801, name: "Improved Lightning Damage Negation +2", desc: "Increases lightning damage negation by 16%" },
  { id: 6002900, name: "Improved Holy Damage Negation +1", desc: "Increases holy damage negation by 15%" },
  { id: 6002901, name: "Improved Holy Damage Negation +2", desc: "Increases holy damage negation by 16%" },
  { id: 6003000, name: "Improved Poison Resistance +1", desc: "Increases poison status resistance by 110" },
  { id: 6003001, name: "Improved Poison Resistance +2", desc: "Increases poison status resistance by 130" },
  { id: 6003100, name: "Improved Blood Loss Resistance +1", desc: "Increases blood loss status resistance by 110" },
  { id: 6003101, name: "Improved Blood Loss Resistance +2", desc: "Increases blood loss status resistance by 130" },
  { id: 6003200, name: "Improved Sleep Resistance +1", desc: "Increases sleep status resistance by 110" },
  { id: 6003201, name: "Improved Sleep Resistance +2", desc: "Increases sleep status resistance by 130" },
  { id: 6003300, name: "Improved Death Blight Resistance +1", desc: "Increases death blight status resistance by 110" },
  { id: 6003301, name: "Improved Death Blight Resistance +2", desc: "Increases death blight status resistance by 130" },
  { id: 6003400, name: "Improved Rot Resistance +1", desc: "Increases rot status resistance by 110" },
  { id: 6003401, name: "Improved Rot Resistance +2", desc: "Increases rot status resistance by 130" },
  { id: 6003500, name: "Improved Frost Resistance +1", desc: "Increases frost status resistance by 110" },
  { id: 6003501, name: "Improved Frost Resistance +2", desc: "Increases frost status resistance by 130" },
  { id: 6003600, name: "Improved Madness Resistance +1", desc: "Increases madness status resistance by 110" },
  { id: 6003601, name: "Improved Madness Resistance +2", desc: "Increases madness status resistance by 130" },
  { id: 6005600, name: "Partial HP Restoration upon Post-Damage Attacks +1", desc: "After taking damage, dealing damage (within about 4 seconds) restores HP, up to the pale section of your health bar. Increased HP gained per hit by 25% compared to +0. Level +1 and +2 stack, but not with other similiar effects." },
  { id: 6005601, name: "Partial HP Restoration upon Post-Damage Attacks +2", desc: "After taking damage, dealing damage (within about 4 seconds) restores HP, up to the pale section of your health bar. Increased HP gained per hit by 35% compared to +0. Level +1 and +2 stack, but not with other similiar effects." },
  { id: 6030200, name: "HP restored when using medicinal boluses, etc. +1", desc: "Restores 33 HP from using certain consumables" },
  { id: 6030201, name: "HP restored when using medicinal boluses, etc. +2", desc: "Restores 40 HP from using certain consumables" },
  { id: 6030600, name: "Successful guarding fills more of the Art gauge +1", desc: "Fills arg gauge by 1.5 upon blocking an attack" },
  { id: 6030800, name: "Critical hits fill more of the Art gauge +1", desc: "Fills art gauge by 6.5 upon riposte" },
  { id: 6030900, name: "Physical attack power increases after using grease items +1", desc: "Increases physical damage by 17% for 30 seconds after using grease" },
  { id: 6030901, name: "Physical attack power increases after using grease items +2", desc: "Increases physical damage by 20% for 30 seconds after using grease" },
  { id: 6035100, name: "Critical Hit Boosts Stamina Recovery Speed +1" },
  { id: 6040100, name: "Improved Guard Counters +1", desc: "Increases guard counter damage by 25%" },
  { id: 6040101, name: "Improved Guard Counters +2", desc: "Increases guard counter damage by 29%" },
  { id: 6040300, name: "Improved Throwing Pot Damage +1", desc: "Increases pot damage by 30%" },
  { id: 6040301, name: "Improved Throwing Pot Damage +2", desc: "Increases pot damage by 35%" },
  { id: 6040400, name: "Improved Throwing Knife Damage +1", desc: "Increases knife damage by 30%" },
  { id: 6040401, name: "Improved Throwing Knife Damage +2", desc: "Increases knife damage by 35%" },
  { id: 6040500, name: "Improved Glintstone and Gravity Stone Damage +1", desc: "Increases stone damage by 30%" },
  { id: 6040501, name: "Improved Glintstone and Gravity Stone Damage +2", desc: "Increases stone damage by 35%" },
  { id: 6043100, name: "Improved Perfuming Arts +1", desc: "Increases Perfuming Arts Damage by +30%." },
  { id: 6060300, name: "Max HP increased for each great enemy defeated at a Great Church.", desc: "Increases maximum HP by 5% for each boss killed at a great church" },
  { id: 6060400, name: "Runes and Item Discovery increased for each great enemy defeated at a Fort", desc: "Increases item discovery by 16 and rune gain by 5.5% for each boss killed at a fort" },
  { id: 6060500, name: "Arcane increased for each great enemy defeated at a Ruin", desc: "Increases arcane by 4 for each boss killed at a ruin" },
  { id: 6060600, name: "Max stamina increased for each great enemy defeated at a Great Encampment", desc: "Increases maximum stamina by 7.5% for each boss killed at a camp" },
  { id: 6090000, name: "Defeating enemies fills more of the Art gauge +1", desc: "Fills art gauge by 6.5 upon killing enemies" },
  { id: 6160000, name: "HP Restoration upon Thrusting Counterattack +1", desc: "Restores 3.3% of Max HP on thrusting counterattacks" },
  { id: 6260000, name: "Attack power up when facing poison-afflicted enemy +1", desc: "Increases damage by 16% when attacking an enemy suffering from poison" },
  { id: 6260001, name: "Attack power up when facing poison-afflicted enemy +2", desc: "Increases damage by 20% when attacking an enemy suffering from poison" },
  { id: 6260300, name: "Attack power up when facing scarlet rot-afflicted enemy +1", desc: "Increases damage by 16% when attacking an enemy suffering from scarlet rot" },
  { id: 6260301, name: "Attack power up when facing scarlet rot-afflicted enemy +2", desc: "Increases damage by 20% when attacking an enemy suffering from scarlet rot" },
  { id: 6260400, name: "Attack power up when facing frostbite-afflicted enemy +1", desc: "Increases damage by 16% when attacking an enemy suffering from frostbite" },
  { id: 6260401, name: "Attack power up when facing frostbite-afflicted enemy +2", desc: "Increases damage by 20% when attacking an enemy suffering from frostbite" },
  { id: 6500000, name: "[Wylder] Character Skill inflicts Blood Loss", desc: "Skill inflicts 60 (impact) and 55 (pull) bleed on hit" },
  { id: 6500100, name: "[Guardian] Character Skill Boosts Damage Negation of Nearby Allies", desc: "Increases damage negation for self and allies by 12% for 30 seconds after using skill" },
  { id: 6500200, name: "[Ironeye] Character Skill Inflicts Heavy Poison Damage on Poisoned Enemies", desc: "Skill deals 0.25% of Max HP + 250 damage on poison-afflicted enemies. Additionally inflicts 70 poison buildup." },
  { id: 6500300, name: "[Duchess] Use Character Skill for Brief Invulnerability", desc: "Makes you immune to damage for 0.4 seconds after using character skill" },
  { id: 6500400, name: "[Raider] Hit With Character Skill to Reduce Enemy Attack Power", desc: "Decreases enemy damage dealt by 13% for 13 seconds after hitting them with skill." },
  { id: 6500500, name: "[Revenant] Increased Max FP upon Ability Activation", desc: "Increases maximum FP by 2% every time passive activates" },
  { id: 6500600, name: "[Recluse] Collect Affinity Residues to Negate Affinity", desc: "Increases magic/fire/lightning/holy damage negation by 20% upon absorbing respective residue" },
  { id: 6500700, name: "[Executor] Slowly Restore HP upon Ability Activation", desc: "Restores (0.27% of Max HP + 3) HP/s for 30 seconds after passive activates" },
  { id: 6500800, name: "[Scholar] Reduced FP consumption when using Character Skill on self", desc: "Reduces FP consumption by 15% for 40 seconds when using Character Skill" },
  { id: 6500900, name: "[Undertaker] Executing Art readies Character Skill" },
  { id: 6600000, name: "Sleep in Vicinity Improves Attack Power", desc: "When nearby enemy or ally is inflicted with sleep, damage increases by 12% for 20 seconds." },
  { id: 6600001, name: "Sleep in Vicinity Improves Attack Power +1", desc: "When nearby enemy or ally is inflicted with sleep, damage increases by 22% for 20 seconds." },
  { id: 6600100, name: "Madness in Vicinity Improves Attack Power", desc: "When nearby enemy or ally is inflicted with madness, damage increases by 12% for 20 seconds." },
  { id: 6600101, name: "Madness in Vicinity Improves Attack Power +1", desc: "When nearby enemy or ally is inflicted with madness, damage increases by 22% for 20 seconds." },
  { id: 6610400, name: "Increased Maximum HP", desc: "Increases maximum HP by 10%" },
  { id: 6610500, name: "Increased Maximum FP", desc: "Increases maximum FP by 15%" },
  { id: 6610600, name: "Increased Maximum Stamina", desc: "Increases maximum stamina by 12%" },
  { id: 6610700, name: "Reduced FP Consumption", desc: "Reduces FP consumption by 8%" },
  { id: 6610800, name: "Improved Affinity Attack Power", desc: "Increases magic, fire, lightning, and holy damage by 5%" },
  { id: 6610801, name: "Improved Affinity Attack Power +1", desc: "Increases magic, fire, lightning, and holy damage by 8%" },
  { id: 6610802, name: "Improved Affinity Attack Power +2", desc: "Increases magic, fire, lightning, and holy damage by 10%" },
  { id: 6611001, name: "Improved Physical Damage Negation +1", desc: "Increases physical damage negation by 10.5%" },
  { id: 6611002, name: "Improved Physical Damage Negation +2", desc: "Increases physical damage negation by 12%" },
  { id: 6611100, name: "Improved Affinity Damage Negation", desc: "Increases magic, fire, lightning, and holy damage negation by 6%" },
  { id: 6611101, name: "Improved Affinity Damage Negation +1", desc: "Increases magic, fire, lightning, and holy damage negation by 10.5%" },
  { id: 6611102, name: "Improved Affinity Damage Negation +2", desc: "Increases magic, fire, lightning, and holy damage negation by 12%" },
  { id: 6611200, name: "Improved Sorceries", desc: "Increases sorcery damage by 5%" },
  { id: 6611201, name: "Improved Sorceries +1", desc: "Increases sorcery damage by 8.5%" },
  { id: 6611202, name: "Improved Sorceries +2", desc: "Increases sorcery damage by 10%" },
  { id: 6611300, name: "Improved Incantations", desc: "Increases incantation damage by 5%" },
  { id: 6611301, name: "Improved Incantations +1", desc: "Increases incantation damage by 8.5%" },
  { id: 6611302, name: "Improved Incantations +2", desc: "Increases incantation damage by 10%" },
  { id: 6611400, name: "Improved Flask HP Restoration", desc: "Increases HP gained from flasks by 10%" },
  { id: 6621000, name: "Crimsonspill Crystal Tear in possession at start of expedition" },
  { id: 6621100, name: "Crimson Crystal Tear in possession at start of expedition" },
  { id: 6621200, name: "Cerulean Crystal Tear in possession at start of expedition" },
  { id: 6621300, name: "Speckled Hardtear in possession at start of expedition" },
  { id: 6621400, name: "Crimson Bubbletear in possession at start of expedition" },
  { id: 6621500, name: "Opaline Bubbletear in possession at start of expedition" },
  { id: 6621600, name: "Crimsonburst Crystal Tear in possession at start of expedition" },
  { id: 6621700, name: "Greenburst Crystal Tear in possession at start of expedition" },
  { id: 6621800, name: "Opaline Hardtear in possession at start of expedition" },
  { id: 6621900, name: "Thorny Cracked Tear in possession at start of expedition" },
  { id: 6622000, name: "Spiked Cracked Tear in possession at start of expedition" },
  { id: 6622100, name: "Windy Crystal Tear in possession at start of expedition" },
  { id: 6622200, name: "Ruptured Crystal Tear in possession at start of expedition" },
  { id: 6622300, name: "Leaden Hardtear in possession at start of expedition" },
  { id: 6622400, name: "Twiggy Cracked Tear in possession at start of expedition" },
  { id: 6622500, name: "Crimsonwhorl Bubbletear in possession at start of expedition" },
  { id: 6622600, name: "Cerulean Hidden Tear in possession at start of expedition" },
  { id: 6622700, name: "Stonebarb Cracked Tear in possession at start of expedition" },
  { id: 6622800, name: "Flame-Shrouding Cracked Tear in possession at start of expedition" },
  { id: 6622900, name: "Magic-Shrouding Cracked Tear in possession at start of expedition" },
  { id: 6623000, name: "Lightning-Shrouding Cracked Tear in possession at start of expedition" },
  { id: 6623100, name: "Holy-Shrouding Cracked Tear in possession at start of expedition" },
  { id: 6623200, name: "Greenspill Crystal Tear in possession at start of expedition" },
  { id: 6624000, name: "Uplifting Aromatic in possession at start of expedition" },
  { id: 6624100, name: "Spark Aromatic in possession at start of expedition" },
  { id: 6624200, name: "Ironjar Aromatic in possession at start of expedition" },
  { id: 6624300, name: "Bloodboil Aromatic in possession at start of expedition" },
  { id: 6624400, name: "Poison Spraymist in possession at start of expedition" },
  { id: 6624500, name: "Acid Spraymist in possession at start of expedition" },
  { id: 6630000, name: "Dormant Power Helps Discover Daggers", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630100, name: "Dormant Power Helps Discover Straight Swords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630200, name: "Dormant Power Helps Discover Greatswords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630300, name: "Dormant Power Helps Discover Colossal Swords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630400, name: "Dormant Power Helps Discover Curved Swords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630500, name: "Dormant Power Helps Discover Curved Greatswords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630600, name: "Dormant Power Helps Discover Katana", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630700, name: "Dormant Power Helps Discover Twinblades", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630800, name: "Dormant Power Helps Discover Thrusting Swords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6630900, name: "Dormant Power Helps Discover Heavy Thrusting Swords", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631000, name: "Dormant Power Helps Discover Axes", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631100, name: "Dormant Power Helps Discover Greataxes", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631200, name: "Dormant Power Helps Discover Hammers", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631300, name: "Dormant Power Helps Discover Great Hammers", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631400, name: "Dormant Power Helps Discover Flails", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631500, name: "Dormant Power Helps Discover Spears", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631600, name: "Dormant Power Helps Discover Great Spears", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631700, name: "Dormant Power Helps Discover Halberds", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631800, name: "Dormant Power Helps Discover Reapers", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6631900, name: "Dormant Power Helps Discover Fists", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632000, name: "Dormant Power Helps Discover Claws", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632100, name: "Dormant Power Helps Discover Whips", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632200, name: "Dormant Power Helps Discover Colossal Weapons", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632300, name: "Dormant Power Helps Discover Bows", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632400, name: "Dormant Power Helps Discover Greatbows", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632500, name: "Dormant Power Helps Discover Crossbows", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632600, name: "Dormant Power Helps Discover Ballistas", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632700, name: "Dormant Power Helps Discover Small Shields", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632800, name: "Dormant Power Helps Discover Medium Shields", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6632900, name: "Dormant Power Helps Discover Greatshields", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6633000, name: "Dormant Power Helps Discover Staves", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6633100, name: "Dormant Power Helps Discover Sacred Seals", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6633200, name: "Dormant Power Helps Discover Torches", desc: "Increases item discovery for the specified weapon. Only the first of these effects is active." },
  { id: 6640000, name: "[Wylder] Improved Mind, Reduced Vigor", desc: "increases mind by 10 and decreases vigor by 5. (At level 12+; scales with lvl)" },
  { id: 6640100, name: "[Wylder] Improved Intelligence and Faith, Reduced Strength and Dexterity", desc: "Increases intelligence and faith by 15. Decreases strength by 7 and dexterity by 5. (At level 12+; scales with lvl)" },
  { id: 6641000, name: "[Guardian] Improved Strength and Dexterity, Reduced Vigor", desc: "Increases strength by 9 and dexterity by 19. Decreases vigor by 8. (At level 12+; scales with lvl)" },
  { id: 6641100, name: "[Guardian] Improved Mind and Faith, Reduced Vigor", desc: "Increases mind by 8 and faith by 17. Decreases vigor by 6. (At level 12+; scales with lvl)" },
  { id: 6642000, name: "[Ironeye] Improved Arcane, Reduced Dexterity", desc: "Increases arcane by 15 and decreases dexterity by 9. (At level 12+; scales with lvl)" },
  { id: 6642100, name: "[Ironeye] Improved Vigor and Strength, Reduced Dexterity", desc: "Increases vigor by 5 and strength by 20. Decreases dexterity by 13. (At level 12+; scales with lvl)" },
  { id: 6643000, name: "[Duchess] Improved Vigor and Strength, Reduced Mind", desc: "Increases vigor by 3 and strength by 24. Decreases mind by 14. (At level 12+; scales with lvl)" },
  { id: 6643100, name: "[Duchess] Improved Mind and Faith, Reduced Intelligence", desc: "Increases mind by 3 and faith by 13. Decreases intelligence by 5. (At level 12+; scales with lvl)" },
  { id: 6644000, name: "[Raider] Improved Mind and Intelligence, Reduced Vigor and Endurance", desc: "increases mind by 9 and intelligence by 35. Decreases vigor by 8 and endurance by 4. (At level 12+; scales with lvl)" },
  { id: 6644100, name: "[Raider] Improved Arcane, Reduced Vigor", desc: "Increases arcane by 17 and decreases vigor by 4. (At level 12+; scales with lvl)" },
  { id: 6645000, name: "[Revenant] Improved Vigor and Endurance, Reduced Mind", desc: "Increases vigor by 5 and endurance by 5. Decreases mind by 11. (At level 12+; scales with lvl)" },
  { id: 6645100, name: "[Revenant] Improved Strength, Reduced Faith", desc: "Increases strength by 25. Decreases faith by 6. (At level 12+; scales with lvl)" },
  { id: 6646000, name: "[Recluse] Improved Vigor, Endurance, and Dexterity, Reduced Intelligence and Faith", desc: "Increases vigor by 4, endurance by 5 and dexterity by 20. Decreases intelligence and faith by 10. (At level 12+; scales with lvl)" },
  { id: 6646100, name: "[Recluse] Improved Intelligence and Faith, Reduced Mind", desc: "Increases intelligence and faith by 12. Decreases mind by 13. (At level 12+; scales with lvl)" },
  { id: 6647000, name: "[Executor] Improved Vigor and Endurance, Reduced Arcane", desc: "Increases vigor by 5 and endurance by 6. Decreases arcane by 13.  (At level 12+; scales with lvl)" },
  { id: 6647100, name: "[Executor] Improved Dexterity and Arcane, Reduced Vigor", desc: "Increases dexterity by 9 and arcane by 12. Decreases vigor by 7. (At level 12+; scales with lvl)" },
  { id: 6647200, name: "[Scholar] Improved Mind, Reduced Vigor", desc: "Increases mind by 9. Decreases vigor by 3. (At level 12+; scales with lvl)" },
  { id: 6647300, name: "[Scholar] Improved Endurance and Dexterity, Reduced Intelligence and Arcane", desc: "Increases endurance by 6 and dexterity by 40. Decreases intelligence by 4 and arcane by 20. (At level 12+; scales with lvl)" },
  { id: 6647400, name: "[Undertaker] Improved Dexterity, Reduced Vigor and Faith", desc: "Increases dexterity by 19. Decreases vigor by 5 and faith by 13. (At level 12+; scales with lvl)" },
  { id: 6647500, name: "[Undertaker] Improved Mind and Faith, Reduced Strength", desc: "Increases mind by 9 and faith by 12. Decreases strength by 15. (At level 12+; scales with lvl)" },
  { id: 6820000, name: "Taking Damage Causes Poison Buildup", desc: "Taking damage inflicts 65 poison buildup" },
  { id: 6820100, name: "Taking Damage Causes Rot Buildup", desc: "Taking damage inflicts 55 rot buildup" },
  { id: 6820200, name: "Taking Damage Causes Frost Buildup", desc: "Taking damage inflicts 55 frost buildup" },
  { id: 6820300, name: "Taking Damage Causes Blood Loss Buildup", desc: "Taking damage inflicts 55 bleed buildup" },
  { id: 6820400, name: "Taking Damage Causes Madness Buildup", desc: "Taking damage inflicts 50 madness buildup" },
  { id: 6820500, name: "Taking Damage Causes Sleep Buildup", desc: "Taking damage inflicts 50 sleep buildup" },
  { id: 6820600, name: "Taking Damage Causes Death Buildup", desc: "Taking damage inflicts 40 deathblight buildup" },
  { id: 6830000, name: "Reduced Strength and Intelligence", desc: "Decreases strength and intelligence by 3" },
  { id: 6830100, name: "Reduced Dexterity and Faith", desc: "Decreases dexterity and faith by 3" },
  { id: 6830200, name: "Reduced Intelligence and Dexterity", desc: "Decreases dexterity and intelligence by 3" },
  { id: 6830300, name: "Reduced Faith and Strength", desc: "Decreases strength and faith by 3" },
  { id: 6830400, name: "Reduced Vigor and Arcane", desc: "Decreases vigor and arcane by 3" },
  { id: 6840000, name: "Reduced Rune Acquisition", desc: "Decreases rune gain by 10%" },
  { id: 6840100, name: "Reduced Flask HP Restoration", desc: "Reduces HP gained from flasks by 15%" },
  { id: 6840200, name: "Ultimate Art Charging Impaired", desc: "Decreases ultimate gauge regen while in combat by 15%" },
  { id: 6850200, name: "All Resistances Down", desc: "Decreases all status resistance by 80" },
  { id: 6850500, name: "Continuous HP Loss", desc: "Decreases HP by 2/s" },
  { id: 6850700, name: "Reduced Damage Negation After Evading", desc: "Decreases damage negations by 45% right after rolling" },
  { id: 6850800, name: "Repeated Evasions Lower Damage Negation", desc: "Decreases damage negations by 35% for 15 seconds on repeat rolls" },
  { id: 6850900, name: "Reduced Damage Negation for Flask Usages", desc: "Decreases damage negations by 45% while using flasks" },
  { id: 6851200, name: "Lower Attack When Below Max HP", desc: "Decreases attack power by 8.5% when below Max HP" },
  { id: 6851300, name: "Poison Buildup When Below Max HP", desc: "Inflicts 3 poison buildup per 0.2s when below Max HP" },
  { id: 6851400, name: "Rot Buildup When Below Max HP", desc: "Inflicts 2 rot buildup per 0.2s when below Max HP" },
  { id: 6851700, name: "Near Death Reduces Max HP", desc: "Reduces maximum HP by 25% for 60 seconds after being downed" },
  { id: 7000000, name: "Vigor +1", desc: "+ 20 Max HP" },
  { id: 7000001, name: "Vigor +2", desc: "+ 40 Max HP" },
  { id: 7000002, name: "Vigor +3", desc: "+ 60 Max HP" },
  { id: 7000090, name: "Increased Maximum HP", desc: "+ 100 Max HP" },
  { id: 7000100, name: "Mind +1", desc: "+ 5 Max FP" },
  { id: 7000101, name: "Mind +2", desc: "+ 10 Max FP" },
  { id: 7000102, name: "Mind +3", desc: "+ 15 Max FP" },
  { id: 7000190, name: "Increased Maximum FP", desc: "+ 25 Max FP" },
  { id: 7000200, name: "Endurance +1", desc: "+ 2 Max Stamina" },
  { id: 7000201, name: "Endurance +2", desc: "+ 4 Max Stamina" },
  { id: 7000202, name: "Endurance +3", desc: "+ 6 Max Stamina" },
  { id: 7000290, name: "Increased Maximum Stamina", desc: "+ 10 Max Stamina" },
  { id: 7000300, name: "Strength +1" },
  { id: 7000301, name: "Strength +2" },
  { id: 7000302, name: "Strength +3" },
  { id: 7000400, name: "Dexterity +1" },
  { id: 7000401, name: "Dexterity +2" },
  { id: 7000402, name: "Dexterity +3" },
  { id: 7000500, name: "Intelligence +1" },
  { id: 7000501, name: "Intelligence +2" },
  { id: 7000502, name: "Intelligence +3" },
  { id: 7000600, name: "Faith +1" },
  { id: 7000601, name: "Faith +2" },
  { id: 7000602, name: "Faith +3" },
  { id: 7000700, name: "Arcane +1" },
  { id: 7000701, name: "Arcane +2" },
  { id: 7000702, name: "Arcane +3" },
  { id: 7000800, name: "Character Skill Cooldown Reduction +1", desc: "Reduces skill cooldown by 5%" },
  { id: 7000801, name: "Character Skill Cooldown Reduction +2", desc: "Reduces skill cooldown by 7.5%" },
  { id: 7000802, name: "Character Skill Cooldown Reduction +3", desc: "Reduces skill cooldown by 10%" },
  { id: 7000900, name: "Ultimate Art Auto Charge +1", desc: "Increases ultimate gauge gain by 5%" },
  { id: 7000901, name: "Ultimate Art Auto Charge +2", desc: "Increases ultimate gauge gain by 7.5%" },
  { id: 7000902, name: "Ultimate Art Auto Charge +3", desc: "Increases ultimate gauge gain by 10%" },
  { id: 7001000, name: "Poise +1", desc: "Reduces incoming poise damage by 5%" },
  { id: 7001001, name: "Poise +2", desc: "Reduces incoming poise damage by 10%" },
  { id: 7001002, name: "Poise +3", desc: "Reduces incoming poise damage by 15%" },
  { id: 7001100, name: "Continuous HP Recovery", desc: "Recovers 2 HP/s." },
  { id: 7001400, name: "Physical Attack Up", desc: "Increases physical damage by 4%" },
  { id: 7001401, name: "Physical Attack Up +1", desc: "Increases physical damage by 5%" },
  { id: 7001402, name: "Physical Attack Up +2", desc: "Increases physical damage by 6%" },
  { id: 7001500, name: "Magic Attack Power Up", desc: "Increases magic damage by 4.5%" },
  { id: 7001501, name: "Magic Attack Power Up +1", desc: "Increases magic damage by 5.5%" },
  { id: 7001502, name: "Magic Attack Power Up +2", desc: "Increases magic damage by 6.5%" },
  { id: 7001600, name: "Fire Attack Power Up", desc: "Increases fire damage by 4.5%" },
  { id: 7001601, name: "Fire Attack Power Up +1", desc: "Increases fire damage by 5.5%" },
  { id: 7001602, name: "Fire Attack Power Up +2", desc: "Increases fire damage by 6.5%" },
  { id: 7001700, name: "Lightning Attack Power Up", desc: "Increases lightning damage by 4.5%" },
  { id: 7001701, name: "Lightning Attack Power Up +1", desc: "Increases lightning damage by 5.5%" },
  { id: 7001702, name: "Lightning Attack Power Up +2", desc: "Increases lightning damage by 6.5%" },
  { id: 7001800, name: "Holy Attack Power Up", desc: "Increases holy damage by 4.5%" },
  { id: 7001801, name: "Holy Attack Power Up +1", desc: "Increases holy damage by 5.5%" },
  { id: 7001802, name: "Holy Attack Power Up +2", desc: "Increases holy damage by 6.5%" },
  { id: 7002600, name: "Magic Damage Negation Up", desc: "Increases magic damage negation by 10%" },
  { id: 7002700, name: "Fire Damage Negation Up", desc: "Increases fire damage negation by 10%" },
  { id: 7002800, name: "Lightning Damage Negation Up", desc: "Increases lightning damage negation by 10%" },
  { id: 7002900, name: "Holy Damage Negation Up", desc: "Increases holy damage negation by 10%" },
  { id: 7003000, name: "Improved Poison Resistance", desc: "Increases poison resistance by 75" },
  { id: 7003100, name: "Improved Blood Loss Resistance", desc: "Increases blood loss resistance by 75" },
  { id: 7003200, name: "Improved Sleep Resistance", desc: "Increases sleep resistance by 75" },
  { id: 7003300, name: "Improved Death Blight Resistance", desc: "Increases death blight resistance by 75" },
  { id: 7003400, name: "Improved Rot Resistance", desc: "Increases rot resistance by 75" },
  { id: 7003500, name: "Improved Frost Resistance", desc: "Increases frost resistance by 75" },
  { id: 7003600, name: "Improved Madness Resistance", desc: "Increases madness resistance by 75" },
  { id: 7005600, name: "Partial HP Restoration upon Post-Damage Attacks", desc: "After taking damage, dealing damage (within about 4 seconds) restores HP, up to the pale section of your health bar. Does not stack with Hand of Malenia, nor Favor of the Rotted Woods." },
  { id: 7006000, name: "Improved Stance-Breaking when Two-Handing", desc: "Increases poise damage by 5% when two-handing the weapon." },
  { id: 7006100, name: "Improved Stance-Breaking when Wielding Two Armaments", desc: "Increases poise damage by 5% when dual wielding 2 weapons of the same type." },
  { id: 7006200, name: "Improved Physical Damage Negation", desc: "Increases physical damage negation by 10%" },
  { id: 7006300, name: "Improved Affinity Damage Negation", desc: "Increases magic, fire, lightning, and holy damage negation by 6%" },
  { id: 7006400, name: "Extended Spell Duration", desc: "Increase duration of spell buffs by 50%" },
  { id: 7006500, name: "Continuous FP Recovery", desc: "Restores 1 FP every 5 seconds" },
  { id: 7006600, name: "Improved Melee Attack Power", desc: "Increases melee damage by 6%" },
  { id: 7006700, name: "Improved Skill Attack Power", desc: "Increases skill damage by 15%" },
  { id: 7010200, name: "Flask Also Heals Allies", desc: "Heals allies for 50% of flask HP in a radius." },
  { id: 7010500, name: "[Wylder] Art activation spreads fire in area" },
  { id: 7010700, name: "[Duchess] Reprise events upon nearby enemies by landing the final blow of a chain attack with dagger", desc: "Restage triggered this way inflicts 36% (1-handed R1) to 39% (2-handed R1 or powerstance L1) of the base damage. It is not affected by \"Improved Character Skill Attack Power\". Only one instance of Restage can be in effect at a time." },
  { id: 7010900, name: "[Revenant] Expend own HP to fully heal nearby allies when activating Art", desc: "Decreases current HP by 50% on ultimate usage." },
  { id: 7011000, name: "[Guardian] Increased duration for Character Skill", desc: "Allows you to briefly charge this skill to trigger a bigger AoE and longer lasting tornado. Can block projectile attacks." },
  { id: 7011200, name: "[Revenant] Trigger ghostflame explosion during Ultimate Art activation" },
  { id: 7011600, name: "[Guardian] Creates whirlwind when charging halberd attacks", desc: "Charged heavy halberd attacks create whirlwinds that do additional damage with slight AOE." },
  { id: 7011700, name: "[Executor] Roaring restores HP while Art is active", desc: "Roar while transformed to heal 15% of max HP to self and nearby allies." },
  { id: 7012000, name: "[Guardian] Slowly restores nearby allies' HP while Art is active", desc: "After landing with Wings of Salvation, continue holding the Ultimate Art button to heal allies within the protective aura for (10% + 12) HP per half second." },
  { id: 7012200, name: "Slowly restore HP for self and nearby allies when HP is low", desc: "When HP falls under 20%, gains a buff that restores HP at a rate of (0.5% + 1) HP per second, for 50 seconds. Does not cancel early if you heal past 20%. Taking an attack that puts you below this threshold resets the duration." },
  { id: 7012300, name: "Improved Damage Negation at Low HP", desc: "Increases damage negation by 16% when HP is below 40%." },
  { id: 7020000, name: "[Wylder] Standard attacks enhanced with fiery follow-ups when using Character Skill (greatsword only)", desc: "Shortly after using Claw Shot, performing a light attack conducts a flaming strike that gives the greatsword additional +12 Fire Damage for 20 seconds." },
  { id: 7030000, name: "Improved Poise Near Totem Stela", desc: "Reduces stance damage by 90% near Totem Stela." },
  { id: 7030200, name: "HP restored when using medicinal boluses, etc.", desc: "Eating cured meats and boluses restores 30 HP." },
  { id: 7030600, name: "Successful guarding fills more of the Art gauge", desc: "Gain 1% Ultimate Art Gauge when guarding." },
  { id: 7030700, name: "Draw enemy attention while guarding", desc: "Draws enemy aggro only after successfully guarding an enemy attack, not when you are in the blocking state." },
  { id: 7030800, name: "Critical hits fill more of the Art gauge", desc: "Gain 5% Ultimate Art Gauge on critical hit." },
  { id: 7030900, name: "Physical attack power increases after using grease items", desc: "+10% damage for 30 seconds after using a grease." },
  { id: 7031200, name: "[Revenant] Strengthens family and allies when Ultimate Art is activated", desc: "After using Immortal March, all family and living allies get +25% damage for 30 seconds." },
  { id: 7031300, name: "[Raider] Damage taken while using Character Skill improves attack power and stamina", desc: "When taking damage during the Retaliate wind-up, +10% damage and +20% Stamina for 20 seconds." },
  { id: 7031800, name: "[Duchess] Become difficult to spot and silence footsteps after landing critical from behind" },
  { id: 7031900, name: "Critical Hits Earn Runes", desc: "Gain 600 runes on critical hits." },
  { id: 7032400, name: "[Wylder] Art gauge greatly filled when ability is activated", desc: "+18% Ultimate Art Gauge after cheating death with Sixth Sense." },
  { id: 7032700, name: "[Duchess] Defeating enemies while Art is active ups attack power", desc: "While invisible after using Finale, gain +15% damage for 30 seconds after any team member kills an enemy." },
  { id: 7032800, name: "[Recluse] Collecting affinity residue activates Terra Magica", desc: "Sigil increases magic damage by 15%, lasts 30s. Cannot spawn a new terra magica while previous one is still active." },
  { id: 7032900, name: "[Recluse] Suffer blood loss and increase attack power upon Art activation", desc: "After activating Soulblood Song, lose 20% of max HP through blood loss and gain an additional +16% damage for 30 seconds." },
  { id: 7033200, name: "[Wylder] +1 additional Character Skill use" },
  { id: 7033400, name: "[Guardian] Successful guards send out shockwaves while ability is active", desc: "Blocking enemy attack with Steel Guard creates small shockwaves that can damage nearby enemies and stagger nearby small enemies." },
  { id: 7034100, name: "[Recluse] Activating Ultimate Art raises Max HP", desc: "After activating Soulblood Song, gain +50% max HP for 30 seconds." },
  { id: 7034400, name: "[Executor] Character Skill Boosts Attack but Lowers Damage Negation While Attacking", desc: "Increases damage by 35% for 6 seconds and lowers damage negation by 40% for 5 seconds" },
  { id: 7034500, name: "[Executor] While Character Skill is active, unlocking use of cursed sword restores HP", desc: "After parrying enough hits for the Cursed Sword to glow, restore 100 HP + 5% of Max HP." },
  { id: 7034600, name: "[Ironeye] Art Charge Activation Adds Poison Effect", desc: "When Single Shot is fully charged, it inflicts 300 Poison buildup to its primary target." },
  { id: 7034700, name: "[Ironeye] Boosts thrusting counterattacks after executing Art", desc: "After executing Single Shot, thrusting counterattacks inflict +20% damage for 30 seconds." },
  { id: 7035100, name: "Critical Hit Boosts Stamina Recovery Speed", desc: "After a critical hit, stamina recovery +10/second for 15 seconds." },
  { id: 7035400, name: "Gesture \"Crossed Legs\" Builds Up Madness", desc: "While the gesture is active, receive 10 Madness buildup every 2 seconds." },
  { id: 7035500, name: "Madness Continually Recovers FP", desc: "After getting inflicted with Madness, regain 2 FP per second for 25 seconds." },
  { id: 7035700, name: "Switching Weapons Adds an Affinity Attack", desc: "When switching weapons, the weapon you switch to is infused with a random element, gaining 12 additional damage for 10 seconds." },
  { id: 7035800, name: "Boosts Attack Power of Added Affinity Attacks", desc: "Increases Affinity Attack Power by 10%" },
  { id: 7035900, name: "Switching Weapons Boosts Attack Power", desc: "Increase physical damage by 10% for 10 seconds after switching weapons." },
  { id: 7036100, name: "HP Recovery From Successful Guarding", desc: "Guarding recovers 15 HP." },
  { id: 7036200, name: "[Scholar] Prevent slowing of Character Skill progress" },
  { id: 7036300, name: "[Scholar] Allies targeted by Character Skill gain boosted attack", desc: "Allies gain 20% physical damage and 15% affinity damage for 30 seconds" },
  { id: 7036400, name: "[Scholar] Continuous damage inflicted on targets threaded by Ultimate Art", desc: "Inflicts 15 damage per second for 20 seconds on targets." },
  { id: 7036500, name: "[Scholar] Earn runes for each additional specimen acquired with Character Skill", desc: "Gain 1300 runes per specimen acquired." },
  { id: 7036800, name: "[Undertaker] Activating Ultimate Art increases attack power", desc: "Increases damage by 14% for 40 seconds when activating Ultimate Art" },
  { id: 7036900, name: "[Undertaker] Attack power increased by landing the final blow of a chain attack", desc: "Increases damage by 16% for 20 seconds when landing the final chain attack" },
  { id: 7037000, name: "[Undertaker] Physical attacks boosted while assist effect from incantation is active for self", desc: "Increases damage by 19% for 60 seconds." },
  { id: 7037300, name: "[Undertaker] Contact with allies restores their HP while Ultimate Art is activated", desc: "Restores allies HP by 100 + 30% of Max HP on contact with Ultimate Art" },
  { id: 7037600, name: "Successive Attacks Boost Attack Power", desc: "Increases damage by 5% / 6.5% / 9% with continuous attacks" },
  { id: 7037700, name: "Status Ailment Gauges Slowly Increase Attack Power" },
  { id: 7037800, name: "Occasionally Nullify Attacks When Damage Negation is Lowered" },
  { id: 7040000, name: "Improved Initial Standard Attack", desc: "Increases the damage of the first light attack by 15%." },
  { id: 7040100, name: "Improved Guard Counters", desc: "Increases guard counter damage by 23%." },
  { id: 7040200, name: "Improved Critical Hits", desc: "Increases critical hit damage by 18%." },
  { id: 7040201, name: "Improved Critical Hits +1", desc: "Increases critical hit damage by 23%. Does not stack with itself." },
  { id: 7040300, name: "Improved Throwing Pot Damage", desc: "Increases Pot Damage by 15%." },
  { id: 7040400, name: "Improved Throwing Knife Damage", desc: "Increases Knife Damage by 15%." },
  { id: 7040500, name: "Improved Glintstone and Gravity Stone Damage", desc: "Increases Stone Damage by 15%." },
  { id: 7043000, name: "Improved Roar & Breath Attacks", desc: "Roar/breath attack damage +15%." },
  { id: 7043100, name: "Improved Perfuming Arts", desc: "Increases Perfuming Arts Damage by +15%." },
  { id: 7043200, name: "Improved Stonedigger Sorcery", desc: "Increases Stonedigger Sorcery damage by +12%." },
  { id: 7043300, name: "Improved Carian Sword Sorcery", desc: "Increases Carian Sword Sorcery damage by +12%." },
  { id: 7043400, name: "Improved Glintblade Sorcery", desc: "Increases Glintblade Sorcery damage by +12%." },
  { id: 7043500, name: "Improved Invisibility Sorcery", desc: "Increases Invisibility Sorcery damage by +12%." },
  { id: 7043600, name: "Improved Crystalian sorcery", desc: "Increases Crystalian Sorcery damage by +12%." },
  { id: 7043700, name: "Improved Gravity Sorcery", desc: "Increases Gravity Sorcery damage by +12%." },
  { id: 7043800, name: "Improved Thorn Sorcery", desc: "Increases Thorn Sorcery damage by +12%." },
  { id: 7043900, name: "Improved Night Sorcery", desc: "Increases Night Sorcery damage by +12%." },
  { id: 7044000, name: "Improved Fundamentalist Incantations", desc: "Increases Fundamentalist Incantations damage by +12%." },
  { id: 7044100, name: "Improved Dragon Cult Incantations", desc: "Increases Dragon Cult Incantations damage by +12%." },
  { id: 7044200, name: "Improved Giants' Flame Incantations", desc: "Increases Giants' Flame Incantations damage by +12%." },
  { id: 7044300, name: "Improved Godslayer Incantations", desc: "Increases Godslayer Incantations damage by +12%." },
  { id: 7044400, name: "Improved Bestial Incantations", desc: "Increases Bestial Incantations damage by +12%." },
  { id: 7044500, name: "Improved Frenzied Flame Incantations", desc: "Increases Frenzied Flame Incantations damage by +12%." },
  { id: 7044600, name: "Improved Dragon Communion Incantations", desc: "Increases Dragon Communion Incantations damage by +12%." },
  { id: 7050000, name: "Raised stamina recovery for nearby allies, but not for self", desc: "Increases allies' stamina recovery speed by 4s." },
  { id: 7050100, name: "Items confer effect to all nearby allies" },
  { id: 7060000, name: "Attack power increased for each evergaol prisoner defeated", desc: "Increases damage by 5% per defeated Evergaol boss." },
  { id: 7060100, name: "Max FP increased for each Sorcerer's Rise unlocked", desc: "Increases max FP by 18% for each Sorcerer's Rise released." },
  { id: 7060200, name: "Attack power increased for each Night Invader defeated", desc: "Increases damage by 7% per defeated invader." },
  { id: 7070000, name: "Treasure marked upon map", desc: "Reveals Buried Treasure on the map." },
  { id: 7080000, name: "Improved Attack Power with 3+ Daggers Equipped", desc: "Increases all damage by 20% with 3 or more Daggers in inventory." },
  { id: 7080100, name: "Improved Attack Power with 3+ Straight Swords Equipped", desc: "Increases all damage by 20% with 3 or more Straight Swords in inventory." },
  { id: 7080200, name: "Improved Attack Power with 3+ Greatswords Equipped", desc: "Increases all damage by 20% with 3 or more Greatswords in inventory." },
  { id: 7080300, name: "Improved Attack Power with 3+ Colossal Swords Equipped", desc: "Increases all damage by 20% with 3 or more Colossal Swords in inventory." },
  { id: 7080400, name: "Improved Attack Power with 3+ Curved Swords Equipped", desc: "Increases all damage by 20% with 3 or more Curved Swords in inventory," },
  { id: 7080500, name: "Improved Attack Power with 3+ Curved Greatswords Equipped", desc: "Increases all damage by 20% with 3 or more Curved Greatswords in inventory." },
  { id: 7080600, name: "Improved Attack Power with 3+ Katana Equipped", desc: "Increases all damage by 20% with 3 or more Katana in inventory." },
  { id: 7080700, name: "Improved Attack Power with 3+ Twinblades Equipped", desc: "Increases all damage by 20% with 3 or more Twinblades in inventory." },
  { id: 7080800, name: "Improved Attack Power with 3+ Thrusting Swords Equipped", desc: "Increases all damage by 20% with 3 or more Thrusting Swords in inventory." },
  { id: 7080900, name: "Improved Attack Power with 3+ Heavy Thrusting Swords Equipped", desc: "Increases all damage by 20% with 3 or more Heavy Thrusting Swords in inventory." },
  { id: 7081000, name: "Improved Attack Power with 3+ Axes Equipped", desc: "Increases all damage by 20% with 3 or more Axes in inventory." },
  { id: 7081100, name: "Improved Attack Power with 3+ Greataxes Equipped", desc: "Increases all damage by 20% with 3 or more Greataxes in inventory." },
  { id: 7081200, name: "Improved Attack Power with 3+ Hammers Equipped", desc: "Increases all damage by 20% with 3 or more Hammers in inventory." },
  { id: 7081300, name: "Improved Attack Power with 3+ Great Hammers Equipped", desc: "Increases all damage by 20% with 3 or more Great Hammers in inventory." },
  { id: 7081400, name: "Improved Attack Power with 3+ Flails Equipped", desc: "Increases all damage by 20% with 3 or more Flails in inventory." },
  { id: 7081500, name: "Improved Attack Power with 3+ Spears Equipped", desc: "Increases all damage by 20% with 3 or more Spears in inventory." },
  { id: 7081700, name: "Improved Attack Power with 3+ Great Spears Equipped", desc: "Increases all damage by 20% with 3 or more Great Spears in inventory." },
  { id: 7081800, name: "Improved Attack Power with 3+ Halberds Equipped", desc: "Increases all damage by 20% with 3 or more Halberds in inventory." },
  { id: 7081900, name: "Improved Attack Power with 3+ Reapers Equipped", desc: "Increases all damage by 20% with 3 or more Reapers in inventory." },
  { id: 7082000, name: "Improved Attack Power with 3+ Fists Equipped", desc: "Increases all damage by 20% with 3 or more Fists in inventory." },
  { id: 7082100, name: "Improved Attack Power with 3+ Claws Equipped", desc: "Increases all damage by 20% with 3 or more Claws in inventory." },
  { id: 7082200, name: "Improved Attack Power with 3+ Whips Equipped", desc: "Increases all damage by 20% with 3 or more Whips in inventory." },
  { id: 7082300, name: "Improved Attack Power with 3+ Colossal Weapons Equipped", desc: "Increases all damage by 20% with 3 or more Colossal Weapons in inventory." },
  { id: 7082400, name: "Improved Attack Power with 3+ Bows Equipped", desc: "Increases all damage by 10% with 3 or more Bows in inventory." },
  { id: 7082500, name: "Max FP Up with 3+ Staves Equipped", desc: "+50 max FP with 3 or more Staves in inventory" },
  { id: 7082600, name: "Max FP Up with 3+ Sacred Seals Equipped", desc: "+50 max FP with 3 or more Sacred Seals in inventory" },
  { id: 7082700, name: "Max HP Up with 3+ Small Shields Equipped", desc: "+200 Max HP with 3 or more Small Shields in inventory" },
  { id: 7082800, name: "Max HP Up with 3+ Medium Shields Equipped", desc: "+200 Max HP with 3 or more Medium Shields in inventory" },
  { id: 7082900, name: "Max HP Up with 3+ Greatshields Equipped", desc: "+200 Max HP with 3 or more Greatshields in inventory" },
  { id: 7090000, name: "Defeating enemies fills more of the Art gauge", desc: "Ultimate Art Gauge increases by 5% for each enemy you kill." },
  { id: 7090100, name: "Defeating enemies restores HP for allies but not for self", desc: "Allies healed for 20 HP when enemies are killed" },
  { id: 7090300, name: "Defeating enemies near Totem Stela restores HP", desc: "Heals 50% of max HP for each enemy defeated near an active Totem Stela." },
  { id: 7100100, name: "Stamina Recovery upon Landing Attacks", desc: "+2 Stamina regained per attack." },
  { id: 7100110, name: "Stamina Recovery upon Landing Attacks +1", desc: "+3 Stamina regained per attack. Stacks with its weaker version." },
  { id: 7110000, name: "Increased rune acquisition for self and allies", desc: "+3.5% rune gain for self and allies" },
  { id: 7120000, name: "Starting armament deals magic damage", desc: "Decreases starting weapon's physical damage by 30/40/50/60 and adds 33/44/55/66 magic damage. The exact amount depends on the weapon type." },
  { id: 7120100, name: "Starting armament deals fire damage", desc: "Decreases starting weapon's physical damage by 30/40/50/60 and adds 33/44/55/66 fire damage. The exact amount depends on the weapon type." },
  { id: 7120200, name: "Starting armament deals lightning damage", desc: "Decreases starting weapon's physical damage by 30/40/50/60 and adds 33/44/55/66 lightning damage. The exact amount depends on the weapon type." },
  { id: 7120300, name: "Starting armament deals holy damage", desc: "Decreases starting weapon's physical damage by 30/40/50/60 and adds 33/44/55/66 holy damage. The exact amount depends on the weapon type." },
  { id: 7120400, name: "Starting armament inflicts frost", desc: "Decreases starting weapon's damage by 15% and add 35 frost buildup." },
  { id: 7120500, name: "Starting armament inflicts poison", desc: "Decreases starting weapon's damage by 15% and add 35 poison buildup." },
  { id: 7120600, name: "Starting armament inflicts blood loss", desc: "Decreases starting weapon's damage by 15% and add 25 blood loss buildup." },
  { id: 7120900, name: "Stonesword Key in possession at start of expedition" },
  { id: 7121000, name: "Small Pouch in possession at start of expedition", desc: "+1 inventory slot during expedition" },
  { id: 7121100, name: "Fire Pots in possession at start of expedition" },
  { id: 7121200, name: "Magic Pots in possession at start of expedition" },
  { id: 7121300, name: "Lightning Pots in possession at start of expedition" },
  { id: 7121400, name: "Holy Water Pots in possession at start of expedition" },
  { id: 7121500, name: "Poisonbone Darts in possession at start of expedition" },
  { id: 7121600, name: "Crystal Darts in possession at start of expedition" },
  { id: 7121700, name: "Throwing Daggers in possession at start of expedition" },
  { id: 7121800, name: "Glintstone Scraps in possession at start of expedition" },
  { id: 7121900, name: "Gravity Stone Chunks in possession at start of expedition" },
  { id: 7122000, name: "Bewitching Branches in possession at start of expedition" },
  { id: 7122100, name: "Wraith Calling Bell in possession at start of expedition", desc: "The effect may stack, but only one bell can be used at a time." },
  { id: 7122200, name: "Fire Grease in possession at start of expedition" },
  { id: 7122300, name: "Magic Grease in possession at start of expedition" },
  { id: 7122400, name: "Lightning Grease in possession at start of expedition" },
  { id: 7122500, name: "Holy Grease in possession at start of expedition" },
  { id: 7122600, name: "Shield Grease in possession at start of expedition" },
  { id: 7122700, name: "Changes compatible armament's skill to Glintblade Phalanx at start of expedition" },
  { id: 7122800, name: "Changes compatible armament's skill to Gravitas at start of expedition" },
  { id: 7122900, name: "Changes compatible armament's skill to Flaming Strike at start of expedition" },
  { id: 7123000, name: "Changes compatible armament's skill to Eruption at start of expedition" },
  { id: 7123100, name: "Changes compatible armament's skill to Thunderbolt at start of expedition" },
  { id: 7123200, name: "Changes compatible armament's skill to Lightning Slash at start of expedition" },
  { id: 7123300, name: "Changes compatible armament's skill to Sacred Blade at start of expedition" },
  { id: 7123400, name: "Changes compatible armament's skill to Prayerful Strike at start of expedition" },
  { id: 7123500, name: "Changes compatible armament's skill to Poisonous Mist at start of expedition" },
  { id: 7123600, name: "Changes compatible armament's skill to Poison Moth Flight at start of expedition" },
  { id: 7123700, name: "Changes compatible armament's skill to Blood Blade at start of expedition" },
  { id: 7123800, name: "Changes compatible armament's skill to Seppuku at start of expedition" },
  { id: 7123900, name: "Changes compatible armament's skill to Chilling Mist at start of expedition" },
  { id: 7124000, name: "Changes compatible armament's skill to Hoarfrost Stomp at start of expedition" },
  { id: 7124100, name: "Changes compatible armament's skill to White Shadow's Lure at start of expedition" },
  { id: 7124300, name: "Changes compatible armament's skill to Endure at start of expedition" },
  { id: 7124400, name: "Changes compatible armament's skill to Quickstep at start of expedition" },
  { id: 7124500, name: "Changes compatible armament's skill to Storm Stomp at start of expedition" },
  { id: 7124600, name: "Changes compatible armament's skill to Determination at start of expedition" },
  { id: 7124700, name: "Changes compatible armament's skill to Rain of Arrows at start of expedition" },
  { id: 7126000, name: "Starlight Shards in possession at start of expedition" },
  { id: 7150000, name: "Guard counter is given a boost based on current HP", desc: "Guard counter does 0.045/0.050/0.055 additional damage per 1 HP. Exact number depends on weapon type." },
  { id: 7160000, name: "HP Restoration upon Thrusting Counterattack", desc: "Restores 2.5% of max HP with thrusting counterattacks" },
  { id: 7170100, name: "Attacks Inflict Rot when Damage is Taken" },
  { id: 7220000, name: "[Revenant] Power up while fighting alongside family", desc: "Helen provides 1 HP/s, Frederick provides 10% damage, and Sebastian provides 20% elemental damage negation" },
  { id: 7230000, name: "Rune discount for shop purchases while on expedition", desc: "Provides a 10% discount at merchants" },
  { id: 7230001, name: "Huge rune discount for shop purchases while on expedition", desc: "Provides a 20% discount at merchants" },
  { id: 7240000, name: "Improved Poise & Damage Negation When Knocked Back by Damage", desc: "After taking damage that knocks you back, reduce damage taken and stance damage taken by 20% for 30 seconds" },
  { id: 7260000, name: "Attack power up when facing poison-afflicted enemy", desc: "+10% damage against poisoned enemies" },
  { id: 7260300, name: "Attack power up when facing scarlet rot-afflicted enemy", desc: "+10% damage against rot-afflicted enemies" },
  { id: 7260400, name: "Attack power up when facing frostbite-afflicted enemy", desc: "+10% damage against frostbitten enemies" },
  { id: 7260700, name: "Frostbite in Vicinity Conceals Self" },
  { id: 7260710, name: "Poison & Rot in Vicinity Increases Attack Power", desc: "When nearby enemy or ally is inflicted with poison or rot, damage increases by 12% for 20 seconds." },
  { id: 7260900, name: "Rot in Vicinity Causes Continuous HP Recovery" },
  { id: 7270100, name: "[Ironeye] +1 additional Character Skill use" },
  { id: 7280000, name: "[Ironeye] Extends duration of weak point", desc: "Marking base duration extended from 17.5 seconds to 22 seconds." },
  { id: 7290000, name: "[Duchess] Improved Character Skill Attack Power", desc: "Increases Restage damage from 50% to 60% of the original damage." },
  { id: 7310000, name: "[Raider] Duration of Ultimate Art extended", desc: "Totem Stela duration increased from 20 seconds to 30 seconds." },
  { id: 7330000, name: "Improved Dagger Attack Power", desc: "Increases Dagger damage by +9%" },
  { id: 7330100, name: "Improved Straight Sword Attack Power", desc: "Increases Straight damage by +9%" },
  { id: 7330200, name: "Improved Greatsword Attack Power", desc: "Increases Greatsword damage by +9%" },
  { id: 7330300, name: "Improved Colossal Sword Attack Power", desc: "Increases Colossal Sword damage by +9%" },
  { id: 7330400, name: "Improved Curved Sword Attack Power", desc: "Increases Curved Sword damage by +9%" },
  { id: 7330500, name: "Improved Curved Greatsword Attack Power", desc: "Increases Curved Greatsword damage by +9%" },
  { id: 7330600, name: "Improved Katana Attack Power", desc: "Increases Katana damage by +9%" },
  { id: 7330700, name: "Improved Twinblade Attack Power", desc: "Increases Twinblade damage by +9%" },
  { id: 7330800, name: "Improved Thrusting Sword Attack Power", desc: "Increases Thrusting Sword damage by +9%" },
  { id: 7330900, name: "Improved Heavy Thrusting Sword Attack Power", desc: "Increases Heavy Thrusting Sword damage by +9%" },
  { id: 7331000, name: "Improved Axe Attack Power", desc: "Increases Axe damage by +9%" },
  { id: 7331100, name: "Improved Greataxe Attack Power", desc: "Increases Greataxe damage by +9%" },
  { id: 7331200, name: "Improved Hammer Attack Power", desc: "Increases Hammer damage by +9%" },
  { id: 7331300, name: "Improved Great Hammer Attack Power", desc: "Increases Great Hammer damage by +9%" },
  { id: 7331400, name: "Improved Flail Attack Power", desc: "Increases Flail damage by +9%" },
  { id: 7331500, name: "Improved Spear Attack Power", desc: "Increases Spear damage by +9%" },
  { id: 7331600, name: "Improved Pike Attack Power", desc: "Increases Pike damage by +9%" },
  { id: 7331700, name: "Improved Great Spear Attack Power", desc: "Increases Great Spear damage by +9%" },
  { id: 7331800, name: "Improved Halberd Attack Power", desc: "Increases Halberd damage by +9%" },
  { id: 7331900, name: "Improved Reaper Attack Power", desc: "Increases Reaper damage by +9%" },
  { id: 7332000, name: "Improved Fist Attack Power", desc: "Increases Fist damage by +9%" },
  { id: 7332100, name: "Improved Claw Attack Power", desc: "Increases Claw damage by +9%" },
  { id: 7332200, name: "Improved Whip Attack Power", desc: "Increases Whip damage by +9%" },
  { id: 7332300, name: "Improved Colossal Weapon Attack Power", desc: "Increases Colossal Weapon damage by +9%" },
  { id: 7332400, name: "Improved Bow Attack Power", desc: "Increases Bow damage by +6%" },
  { id: 7340000, name: "HP Restoration upon Dagger Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340100, name: "HP Restoration upon Straight Sword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340200, name: "HP Restoration upon Greatsword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340300, name: "HP Restoration upon Colossal Sword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340400, name: "HP Restoration upon Curved Sword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340500, name: "HP Restoration upon Curved Greatsword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340600, name: "HP Restoration upon Katana Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340700, name: "HP Restoration upon Twinblade Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340800, name: "HP Restoration upon Thrusting Sword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7340900, name: "HP Restoration upon Heavy Thrusting Sword Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341000, name: "HP Restoration upon Axe Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341100, name: "HP Restoration upon Greataxe Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341200, name: "HP Restoration upon Hammer Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341300, name: "HP Restoration upon Great Hammer Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341400, name: "HP Restoration upon Flail Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341500, name: "HP Restoration upon Spear Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341600, name: "HP Restoration upon Pike Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341700, name: "HP Restoration upon Great Spear Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341800, name: "HP Restoration upon Halberd Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7341900, name: "HP Restoration upon Reaper Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7342000, name: "HP Restoration upon Fist Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7342100, name: "HP Restoration upon Claw Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7342200, name: "HP Restoration upon Whip Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7342300, name: "HP Restoration upon Colossal Weapon Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7342400, name: "HP Restoration upon Bow Attacks", desc: "Restores 15 HP with each attack with the weapon type." },
  { id: 7350000, name: "FP Restoration upon Dagger Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350100, name: "FP Restoration upon Straight Sword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350200, name: "FP Restoration upon Greatsword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350300, name: "FP Restoration upon Colossal Sword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350400, name: "FP Restoration upon Curved Sword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350500, name: "FP Restoration upon Curved Greatsword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350600, name: "FP Restoration upon Katana Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350700, name: "FP Restoration upon Twinblade Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350800, name: "FP Restoration upon Thrusting Sword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7350900, name: "FP Restoration upon Heavy Thrusting Sword Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351000, name: "FP Restoration upon Axe Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351100, name: "FP Restoration upon Greataxe Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351200, name: "FP Restoration upon Hammer Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351300, name: "FP Restoration upon Great Hammer Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351400, name: "FP Restoration upon Flail Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351500, name: "FP Restoration upon Spear Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351600, name: "FP Restoration upon Pike Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351700, name: "FP Restoration upon Great Spear Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351800, name: "FP Restoration upon Halberd Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7351900, name: "FP Restoration upon Reaper Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7352000, name: "FP Restoration upon Fist Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7352100, name: "FP Restoration upon Claw Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7352200, name: "FP Restoration upon Whip Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7352300, name: "FP Restoration upon Colossal Weapon Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7352400, name: "FP Restoration upon Bow Attacks", desc: "Restores 2 FP with each attack with the weapon type." },
  { id: 7360600, name: "Changes compatible armament's sorcery to Magic Glintblade at start of expedition" },
  { id: 7360900, name: "Changes compatible armament's sorcery to Carian Greatsword at start of expedition" },
  { id: 7361200, name: "Changes compatible armament's sorcery to Night Shard at start of expedition" },
  { id: 7361300, name: "Changes compatible armament's sorcery to Magma Shot at start of expedition" },
  { id: 7361500, name: "Changes compatible armament's sorcery to Glintstone Icecrag at start of expedition" },
  { id: 7361800, name: "Changes compatible armament's sorcery to Gravity Well at start of expedition" },
  { id: 7362100, name: "Changes compatible armament's sorcery to Briars of Punishment at start of expedition" },
  { id: 7370000, name: "Changes compatible armament's incantation to Blessing's Boon at start of expedition" },
  { id: 7370200, name: "Changes compatible armament's incantation to Aspects of the Crucible: Horns at start of expedition" },
  { id: 7370300, name: "Changes compatible armament's incantation to Wrath of Gold at start of expedition" },
  { id: 7370400, name: "Changes compatible armament's incantation to Lightning Spear at start of expedition" },
  { id: 7370500, name: "Changes compatible armament's incantation to Lightning Strike at start of expedition" },
  { id: 7370600, name: "Changes compatible armament's incantation to O, Flame! at start of expedition" },
  { id: 7370800, name: "Changes compatible armament's incantation to Black Flame at start of expedition" },
  { id: 7370900, name: "Changes compatible armament's incantation to Beast Claw at start of expedition" },
  { id: 7371200, name: "Changes compatible armament's incantation to Swarm of Flies at start of expedition" },
  { id: 7371500, name: "Changes compatible armament's incantation to Dragonfire at start of expedition" },
];
